USE Session09
GO
CREATE TABLE Student
(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Name NVARCHAR(50) NOT NULL,
	Family NVARCHAR(50) NOT NULL,
)
GO
CREATE TABLE Course
(
	Id INT IDENTITY,
	Title NVARCHAR(50) NOT NULL UNIQUE,
	PRIMARY KEY(Id)
)
GO
CREATE TABLE Student_Course
(
	CourseId INT FOREIGN KEY REFERENCES Course(Id),
	StudentId INT,
	CONSTRAINT PK_StudentCourse PRIMARY KEY(CourseId,StudentId),
	CONSTRAINT FK_StudentId_Student_Id FOREIGN KEY(StudentId) REFERENCES Student(Id)
)